INSERT INTO ROLE(ROLE) VALUES ('ADMIN');
INSERT INTO USERS (ACTIVE,PASSWORD,USER_NAME) VALUES (1,'$2a$10$5OkeCLKNs/BkdO0qcYRri.MdIcKhFvElAllhPgLfRQqG7wkEiPmq2','huaweiturkey');
INSERT INTO USER_ROLE(USER_ID,ROLE_ID) VALUES(1,1);